### PR TITLE
upgrade to broccoli-persistent-filter

### PR DESCRIPTION
**Pull request by stefanpenner**
- faster rebuilds
- lower cost for initial builds

Note: this is for 1.6x

### CODE REVIEW

**Comment by toranb** [comment]
conflicts ?

**Comment by stefanpenner** [comment]
@toranb well, there isn't a branch for 1.6.x. If you are +1, i can make one.

**Comment by toranb** [comment]
if you have some bandwidth to support 1.6 -create the branch for it boss :)

**Comment by stefanpenner** [comment]
1.6.3 released and 1.6.x branch opened.

**Pull request closed without merging**
